use_frameworks!

platform :ios, '9.0'

target 'JSBaseAlertView_Example' do
  pod 'JSBaseAlertView', :path => '../'

  target 'JSBaseAlertView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
